### ISSUE TITLE
Why is there no APK client?

### ISSUE THREAD

**Issue by iiya2** [Solaree/V12#1]

**Comment by Solaree** [comment]
If you want the client, here (made by VitalikObject): https://drive.google.com/file/d/17P7LdvUn8yIjem_xaTHn-wB92RY6iGol/view?usp=sharing

**You can use another client, it's not hard to find it**

**Comment by iiya2** [comment]
Ok thanks!

вт, 7 февр. 2023 г., 22:10 Solar ***@***.***>:
